// src/routes/(app)/admin/usuarios/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';
	import { toast } from 'svelte-sonner';

	export let data: any;
	export let form: any;

	// Colores por rol para los badges
	const rolColors: Record<string, string> = {
		ADMIN: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
		INVESTIGADOR: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
		USUARIO: 'bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300'
	};

	const rolLabels: Record<string, string> = {
		ADMIN: 'Administrador',
		INVESTIGADOR: 'Investigador',
		USUARIO: 'Usuario'
	};

	$: if (form?.success) {
		toast.success('Operación exitosa', { description: form?.message });
	} else if (form?.error) {
		toast.error('Error', { description: form?.message });
	}
</script>

<svelte:head>
	<title>Administrar Usuarios | Plataforma Idea 2025</title>
</svelte:head>

<div class="space-y-6">
	<div>
		<h1 class="text-3xl font-bold tracking-tight">Administrar Usuarios</h1>
		<p class="text-slate-500 mt-1">Gestionar roles y accesos de los usuarios de la plataforma</p>
	</div>

	<!-- Resumen de usuarios por rol -->
	<div class="grid gap-4 md:grid-cols-3">
		<Card.Root>
			<Card.Header class="flex flex-row items-center justify-between space-y-0 pb-2">
				<Card.Title class="text-sm font-medium">Total Usuarios</Card.Title>
				<svg class="h-4 w-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z" />
				</svg>
			</Card.Header>
			<Card.Content>
				<div class="text-2xl font-bold">{data.usuarios.length}</div>
				<p class="text-xs text-slate-500">Registrados en la plataforma</p>
			</Card.Content>
		</Card.Root>

		<Card.Root>
			<Card.Header class="flex flex-row items-center justify-between space-y-0 pb-2">
				<Card.Title class="text-sm font-medium">Investigadores</Card.Title>
				<svg class="h-4 w-4 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
				</svg>
			</Card.Header>
			<Card.Content>
				<div class="text-2xl font-bold">{data.usuarios.filter((u: any) => u.rol === 'INVESTIGADOR').length}</div>
				<p class="text-xs text-slate-500">Con acceso a datos globales</p>
			</Card.Content>
		</Card.Root>

		<Card.Root>
			<Card.Header class="flex flex-row items-center justify-between space-y-0 pb-2">
				<Card.Title class="text-sm font-medium">Administradores</Card.Title>
				<svg class="h-4 w-4 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
				</svg>
			</Card.Header>
			<Card.Content>
				<div class="text-2xl font-bold">{data.usuarios.filter((u: any) => u.rol === 'ADMIN').length}</div>
				<p class="text-xs text-slate-500">Con control total</p>
			</Card.Content>
		</Card.Root>
	</div>

	<!-- Tabla de usuarios -->
	<Card.Root>
		<Card.Header>
			<Card.Title>Usuarios Registrados</Card.Title>
			<Card.Description>Cambia el rol o estado de cualquier usuario de la plataforma</Card.Description>
		</Card.Header>
		<Card.Content>
			<div class="overflow-x-auto">
				<table class="w-full text-sm">
					<thead>
						<tr class="border-b text-left">
							<th class="pb-3 font-medium text-slate-500">Nombre</th>
							<th class="pb-3 font-medium text-slate-500">Email</th>
							<th class="pb-3 font-medium text-slate-500">Rol</th>
							<th class="pb-3 font-medium text-slate-500">Estado</th>
							<th class="pb-3 font-medium text-slate-500">Registro</th>
							<th class="pb-3 font-medium text-slate-500 text-right">Acciones</th>
						</tr>
					</thead>
					<tbody>
						{#each data.usuarios as usuario (usuario.id)}
							<tr class="border-b last:border-0 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
								<td class="py-3 font-medium">{usuario.nombre}</td>
								<td class="py-3 text-slate-600 dark:text-slate-400">{usuario.email}</td>
								<td class="py-3">
									{#if usuario.id !== data.user?.userId}
										<form method="POST" action="?/updateRole" use:enhance class="inline">
											<input type="hidden" name="userId" value={usuario.id} />
											<select
												name="rol"
												class="text-xs font-semibold rounded-full px-3 py-1 border-0 cursor-pointer appearance-none {rolColors[usuario.rol] || rolColors['USUARIO']}"
												value={usuario.rol}
												on:change={(e) => e.currentTarget.form?.requestSubmit()}
											>
												<option value="USUARIO">Usuario</option>
												<option value="INVESTIGADOR">Investigador</option>
												<option value="ADMIN">Administrador</option>
											</select>
										</form>
									{:else}
										<span class="text-xs font-semibold rounded-full px-3 py-1 {rolColors[usuario.rol]}">
											{rolLabels[usuario.rol] || usuario.rol}
										</span>
										<span class="text-xs text-slate-400 ml-1">(tú)</span>
									{/if}
								</td>
								<td class="py-3">
									{#if usuario.activo}
										<span class="inline-flex items-center gap-1 text-xs font-medium text-green-700 dark:text-green-400">
											<span class="h-2 w-2 rounded-full bg-green-500"></span>
											Activo
										</span>
									{:else}
										<span class="inline-flex items-center gap-1 text-xs font-medium text-slate-400">
											<span class="h-2 w-2 rounded-full bg-slate-300"></span>
											Inactivo
										</span>
									{/if}
								</td>
								<td class="py-3 text-slate-500 text-xs">
									{usuario.createdAt ? new Date(usuario.createdAt).toLocaleDateString('es-CL') : '—'}
								</td>
								<td class="py-3 text-right">
									{#if usuario.id !== data.user?.userId}
										<form method="POST" action="?/toggleActive" use:enhance class="inline">
											<input type="hidden" name="userId" value={usuario.id} />
											<input type="hidden" name="activo" value={!usuario.activo} />
											<Button
												type="submit"
												variant="ghost"
												class="h-8 text-xs {usuario.activo ? 'text-red-600 hover:text-red-700 hover:bg-red-50' : 'text-green-600 hover:text-green-700 hover:bg-green-50'}"
											>
												{usuario.activo ? 'Desactivar' : 'Activar'}
											</Button>
										</form>
									{:else}
										<span class="text-xs text-slate-400">—</span>
									{/if}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</Card.Content>
	</Card.Root>
</div>

// app/dashboard/usuarios/page.tsx
"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Loader2, Search, UserCheck, UserMinus, Shield, User as UserIcon, Microscope, UserPlus } from "lucide-react"
import { Modal } from "@/components/ui/modal"
import { Label } from "@/components/ui/label"

interface Usuario {
    id: number
    nombre: string
    email: string
    rol: "ADMIN" | "INVESTIGADOR" | "PUBLICO"
    activo: boolean
    created_at: string
    _count: {
        mediciones: number
        lugares: number
        unidades: number
    }
}

export default function UsuariosPage() {
    const [usuarios, setUsuarios] = useState<Usuario[]>([])
    const [loading, setLoading] = useState(true)
    const [search, setSearch] = useState("")

    // Modal state
    const [isModalOpen, setIsModalOpen] = useState(false)
    const [isSubmitting, setIsSubmitting] = useState(false)
    const [formData, setFormData] = useState({
        nombre: "",
        email: "",
        password: "",
        rol: "PUBLICO"
    })

    const fetchUsuarios = async () => {
        setLoading(true)
        try {
            const token = localStorage.getItem("token")
            const res = await fetch(`/api/usuarios?q=${search}&inactivos=true`, {
                headers: { "Authorization": `Bearer ${token}` }
            })
            const data = await res.json()
            if (data.success) setUsuarios(data.data)
        } catch (error) {
            console.error(error)
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        fetchUsuarios()
    }, [search])

    const updateUsuario = async (id: number, data: Partial<Usuario>) => {
        try {
            const token = localStorage.getItem("token")
            const res = await fetch(`/api/usuarios/${id}`, {
                method: "PATCH",
                headers: {
                    "Authorization": `Bearer ${token}`,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(data)
            })
            const result = await res.json()
            if (result.success) {
                fetchUsuarios()
            } else {
                alert(result.message)
            }
        } catch (error) {
            console.error(error)
        }
    }

    const handleCreateUser = async (e: React.FormEvent) => {
        e.preventDefault()
        setIsSubmitting(true)
        try {
            const token = localStorage.getItem("token")
            const res = await fetch("/api/usuarios", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${token}`,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(formData)
            })
            const data = await res.json()
            if (data.success) {
                setIsModalOpen(false)
                setFormData({ nombre: "", email: "", password: "", rol: "PUBLICO" })
                fetchUsuarios()
            } else {
                alert(data.message)
            }
        } catch (error) {
            console.error(error)
            alert("Error al crear usuario")
        } finally {
            setIsSubmitting(false)
        }
    }

    const RoleBadge = ({ rol }: { rol: string }) => {
        switch (rol) {
            case "ADMIN":
                return <span className="flex items-center gap-1.5 text-violet-500 font-bold"><Shield className="w-3 h-3" /> ADMIN</span>
            case "INVESTIGADOR":
                return <span className="flex items-center gap-1.5 text-blue-500 font-bold"><Microscope className="w-3 h-3" /> INVESTIGADOR</span>
            default:
                return <span className="flex items-center gap-1.5 text-slate-500 font-bold"><UserIcon className="w-3 h-3" /> PÚBLICO</span>
        }
    }

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight font-outfit">Gestión de Usuarios</h2>
                    <p className="text-muted-foreground">Administra los accesos y roles del personal.</p>
                </div>
                <Button onClick={() => setIsModalOpen(true)} className="gap-2 shadow-lg shadow-primary/20">
                    <UserPlus className="w-4 h-4" />
                    Nuevo Usuario
                </Button>
            </div>

            <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
                <CardHeader className="p-4 border-b text-center sm:text-left">
                    <div className="relative max-w-sm">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                        <Input
                            placeholder="Buscar por nombre o email..."
                            className="pl-10"
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                        />
                    </div>
                </CardHeader>
                <CardContent className="p-0">
                    <Table>
                        <TableHeader>
                            <TableRow className="bg-muted/30">
                                <TableHead>Usuario</TableHead>
                                <TableHead>Rol</TableHead>
                                <TableHead>Estado</TableHead>
                                <TableHead>Actividad</TableHead>
                                <TableHead className="text-right">Acciones</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {loading && usuarios.length === 0 ? (
                                <TableRow>
                                    <TableCell colSpan={5} className="h-40 text-center">
                                        <Loader2 className="w-8 h-8 animate-spin mx-auto text-primary opacity-50" />
                                    </TableCell>
                                </TableRow>
                            ) : usuarios.length === 0 ? (
                                <TableRow>
                                    <TableCell colSpan={5} className="h-40 text-center text-muted-foreground">
                                        No se encontraron usuarios.
                                    </TableCell>
                                </TableRow>
                            ) : (
                                usuarios.map((u) => (
                                    <TableRow key={u.id} className="group transition-colors hover:bg-muted/30">
                                        <TableCell>
                                            <div className="flex items-center gap-3">
                                                <div className="w-9 h-9 rounded-full bg-primary/10 flex items-center justify-center border border-primary/20">
                                                    <span className="font-bold text-primary text-xs">{u.nombre?.[0].toUpperCase()}</span>
                                                </div>
                                                <div className="flex flex-col">
                                                    <span className="font-medium text-sm">{u.nombre}</span>
                                                    <span className="text-xs text-muted-foreground">{u.email}</span>
                                                </div>
                                            </div>
                                        </TableCell>
                                        <TableCell>
                                            <div className="flex items-center gap-2">
                                                <select
                                                    className="bg-transparent text-xs font-semibold focus:outline-none cursor-pointer border-b border-transparent hover:border-primary/30 transition-colors py-1"
                                                    value={u.rol}
                                                    onChange={(e) => updateUsuario(u.id, { rol: e.target.value as any })}
                                                >
                                                    <option value="ADMIN">ADMIN</option>
                                                    <option value="INVESTIGADOR">INVESTIGADOR</option>
                                                    <option value="PUBLICO">PÚBLICO</option>
                                                </select>
                                                <div className="opacity-50 group-hover:opacity-100 transition-opacity">
                                                    <RoleBadge rol={u.rol} />
                                                </div>
                                            </div>
                                        </TableCell>
                                        <TableCell>
                                            <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-bold border ${u.activo ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20' : 'bg-rose-500/10 text-rose-500 border-rose-500/20'}`}>
                                                {u.activo ? 'ACTIVO' : 'INACTIVO'}
                                            </span>
                                        </TableCell>
                                        <TableCell>
                                            <div className="flex flex-col text-[11px] text-muted-foreground">
                                                <span>{u._count.mediciones} Mediciones</span>
                                                <span className="text-[10px] opacity-60">ID: {u.id}</span>
                                            </div>
                                        </TableCell>
                                        <TableCell className="text-right">
                                            <Button
                                                variant="ghost"
                                                size="sm"
                                                className={`gap-2 ${u.activo ? 'hover:text-rose-500 hover:bg-rose-500/10' : 'hover:text-emerald-500 hover:bg-emerald-500/10'}`}
                                                onClick={() => updateUsuario(u.id, { activo: !u.activo })}
                                            >
                                                {u.activo ? (
                                                    <><UserMinus className="w-4 h-4" /> Desactivar</>
                                                ) : (
                                                    <><UserCheck className="w-4 h-4" /> Activar</>
                                                )}
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))
                            )}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>

            {/* Modal para Nuevo Usuario */}
            <Modal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                title="Crear Nuevo Usuario"
                description="Ingresa los datos del nuevo miembro del equipo."
            >
                <form onSubmit={handleCreateUser} className="space-y-4">
                    <div className="space-y-2">
                        <Label htmlFor="nombre">Nombre Completo</Label>
                        <Input
                            id="nombre"
                            placeholder="Ej. Juan Pérez"
                            required
                            value={formData.nombre}
                            onChange={(e) => setFormData({ ...formData, nombre: e.target.value })}
                        />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="email">Correo Electrónico</Label>
                        <Input
                            id="email"
                            type="email"
                            placeholder="usuario@ejemplo.com"
                            required
                            value={formData.email}
                            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                        />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="password">Contraseña</Label>
                        <Input
                            id="password"
                            type="password"
                            placeholder="••••••••"
                            required
                            value={formData.password}
                            onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                        />
                    </div>
                    <div className="space-y-2">
                        <Label htmlFor="rol">Rol del Usuario</Label>
                        <select
                            id="rol"
                            className="w-full flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                            value={formData.rol}
                            onChange={(e) => setFormData({ ...formData, rol: e.target.value })}
                        >
                            <option value="PUBLICO">Público (Acceso limitado)</option>
                            <option value="INVESTIGADOR">Investigador (Mediciones y Análisis)</option>
                            <option value="ADMIN">Administrador (Control total)</option>
                        </select>
                    </div>
                    <div className="flex justify-end gap-3 pt-4">
                        <Button type="button" variant="ghost" onClick={() => setIsModalOpen(false)}>
                            Cancelar
                        </Button>
                        <Button type="submit" disabled={isSubmitting}>
                            {isSubmitting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <UserPlus className="w-4 h-4 mr-2" />}
                            Crear Usuario
                        </Button>
                    </div>
                </form>
            </Modal>
        </div>
    )
}
